In [1]:
#library import
import numpy as np

In [17]:
arr=[[1,2,3],[4,5,6]]
result= arr*2
print (result)

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


In [19]:
arr=np.array([[1,2,3],[4,5,6]])
result= arr*2
print (result)

[[ 2  4  6]
 [ 8 10 12]]


In [113]:
arr = np.array([[-1, 2, 0, 4, 6], 
                [4, -0.5, 6, 0,9], 
                [2.6, 0, 7, 8,4], 
                [3, -7, 4, 2.0,3]]) 
print("Dimension of array",arr.ndim)
print("Shape of array",arr.shape)
print()
print("Transpose of the array",arr.T, "\n")
print("Element on row 2 and column 2: ",arr[2][2], "\n")
print("Elements start from 0 to 4 , with three jump of row",arr[:4][::3], "\n")
print("Elements in range of row 0 and 4, with two jump of column",arr[0:4,::2], "\n")

Dimension of array 2
Shape of array (4, 5)

Transpose of the array [[-1.   4.   2.6  3. ]
 [ 2.  -0.5  0.  -7. ]
 [ 0.   6.   7.   4. ]
 [ 4.   0.   8.   2. ]
 [ 6.   9.   4.   3. ]] 

Element on row 2 and column 2:  7.0 

Elements start from 0 to 4 , with three jump of row [[-1.  2.  0.  4.  6.]
 [ 3. -7.  4.  2.  3.]] 

Elements in range of row 0 and 4, with two jump of column [[-1.   0.   6. ]
 [ 4.   6.   9. ]
 [ 2.6  7.   4. ]
 [ 3.   4.   3. ]] 



In [120]:
#Reshape arrray
reshaped = arr.reshape(2,10)
print(reshaped)

[[-1.   2.   0.   4.   6.   4.  -0.5  6.   0.   9. ]
 [ 2.6  0.   7.   8.   4.   3.  -7.   4.   2.   3. ]]


In [122]:
#Copy array
arr1= reshaped.copy()
print(arr1)

[[-1.   2.   0.   4.   6.   4.  -0.5  6.   0.   9. ]
 [ 2.6  0.   7.   8.   4.   3.  -7.   4.   2.   3. ]]


In [75]:
#3D array
a=np.array([[[1,2],[2.3,4], [4,5]]])
print("Dimention of array a :",a.ndim)
print("Data type of array a :",a.dtype)
print("Sum of a =", a.sum())
print("Square root of a =", np.sqrt(a),"\n")

b=np.array([[[6,7],[8,9],[10,11]]])
print("Dimention of array b :",b.ndim)
print("Data type of array b :",b.dtype)
print("Sum of b =", np.sum(b))
print("Square root of b =", np.sqrt(a), "\n")
print("Sum of a and b", a+b)



Dimention of array a : 3
Data type of array a : float64
Sum of a = 18.3
Square root of a = [[[1.         1.41421356]
  [1.51657509 2.        ]
  [2.         2.23606798]]] 

Dimention of array b : 3
Data type of array b : int64
Sum of b = 51
Square root of b = [[[1.         1.41421356]
  [1.51657509 2.        ]
  [2.         2.23606798]]] 

Sum of a and b [[[ 7.   9. ]
  [10.3 13. ]
  [14.  16. ]]]
